service:
  host: localhost
  port: 8001

kafka:
  host: localhost
  port: 29092
  topic-products: products
  topic-debts: debts

mongodb:
  host: localhost
  port: 27017
  database: productdb
  collection: products
