// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type DebtDashboard struct {
	ID        uuid.UUID
	DebtID    string
	DebtPrice int32
	PaidPrice int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullInt64
}

type ProductDashboard struct {
	ID        uuid.UUID
	ProductID string
	Color     string
	Price     int32
	PaidPrice int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullInt64
}
