service:
  host: localhost
  port: 8003

kafka:
  host: localhost
  port: 29092
  topic-products: products
  topic-debts: debts

postgres:
  host: localhost
  port: 5432
  dbname: debtsdb
  user: postgres
  password: 1